### ISSUE TITLE
Small Issue: 'model.predict' may not parse tracker's configuration

### ISSUE THREAD

**Issue by lizi-Margin** [SunOner/sunone_aimbot#271]
According to the source code of Ultralytics, the method 'model.predict' may not parse tracker's configuration, though this won't cause any problem.
```python
@torch.inference_mode()
def perform_detection(model, image, tracker=None):
    if tracker is not None:
        results = model.predict(
            source=image,
            cfg="logic/tracker.yaml",  # <- traker's configuration file
            imgsz=cfg.ai_model_image_size,
            stream=True,
            conf=cfg.AI_conf,
            iou=0.5,
            device=cfg.AI_device,
            half=False if "cpu" in cfg.AI_device else True,
            max_det=20,
            agnostic_nms=False,
            augment=False,
            vid_stride=False,
            visualize=False,
            verbose=False,
            show_boxes=False,
            show_labels=False,
            show_conf=False,
            save=False,
            show=False)
```
So these configurations in logic/tracker.yaml may not make any difference.
``` yaml
tracker_type: bytetrack # tracker type, ['botsort', 'bytetrack']  change this to select tracker
track_high_thresh: 0.25 # threshold for the first association
track_low_thresh: 0.1 # threshold for the second association
new_track_thresh: 0.25 # threshold for init new track if the detection does not match any tracks
track_buffer: 30 # buffer to calculate the time when to remove tracks
match_thresh: 0.8 # threshold for matching tracks
fuse_score: True # Whether to fuse confidence scores with the iou distances before matching
# min_box_area: 10  # threshold for min box areas(for tracker evaluation, not used for now)

# BoT-SORT settings
gmc_method: sparseOptFlow # method of global motion compensation
# ReID model related thresh (not supported yet)
proximity_thresh: 0.5
appearance_thresh: 0.25
with_reid: False
```
